create table audit_runs (
    job_id varchar(64) primary key,
    target_url text not null,
    status varchar(32) not null,
    created_at timestamp with time zone not null,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    failure_message text
);

create table audit_events (
    id bigint generated by default as identity primary key,
    job_id varchar(64) not null,
    sequence bigint not null,
    event_type varchar(32) not null,
    status varchar(32),
    payload_json text not null,
    created_at timestamp with time zone not null,
    constraint fk_audit_events_run foreign key (job_id) references audit_runs (job_id),
    constraint uk_audit_events_job_sequence unique (job_id, sequence)
);

create index idx_audit_events_job_sequence on audit_events (job_id, sequence);

create table audit_reports (
    job_id varchar(64) primary key,
    generated_at timestamp with time zone not null,
    report_json text not null,
    signature_algorithm varchar(64) not null,
    signature_value text not null,
    constraint fk_audit_reports_run foreign key (job_id) references audit_runs (job_id)
);
