alter table audit_runs
    add column normalized_url text;

alter table audit_runs
    add column normalized_host varchar(255);

alter table audit_runs
    add column normalized_path text;

create table projects (
    id uuid primary key,
    owner_user_id uuid not null,
    name varchar(160) not null,
    slug varchar(191) not null,
    description text,
    scope_type varchar(32) not null,
    scope_value text not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_projects_owner_user foreign key (owner_user_id) references auth_users (id),
    constraint uk_projects_owner_slug unique (owner_user_id, slug)
);

create index idx_projects_owner_created_at
    on projects (owner_user_id, created_at desc);

create table project_tracked_urls (
    id uuid primary key,
    project_id uuid not null,
    normalized_url text not null,
    normalized_host varchar(255) not null,
    normalized_path text not null,
    display_url text not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_project_tracked_urls_project foreign key (project_id) references projects (id) on delete cascade,
    constraint uk_project_tracked_urls_project_url unique (project_id, normalized_url)
);

create index idx_project_tracked_urls_project_created_at
    on project_tracked_urls (project_id, created_at desc);

create table audit_project_links (
    job_id varchar(64) primary key,
    project_id uuid not null,
    tracked_url_id uuid not null,
    linked_at timestamp with time zone not null,
    linked_by_user_id uuid not null,
    constraint fk_audit_project_links_run foreign key (job_id) references audit_runs (job_id) on delete cascade,
    constraint fk_audit_project_links_project foreign key (project_id) references projects (id) on delete cascade,
    constraint fk_audit_project_links_tracked_url foreign key (tracked_url_id) references project_tracked_urls (id) on delete cascade,
    constraint fk_audit_project_links_linked_by_user foreign key (linked_by_user_id) references auth_users (id)
);

create index idx_audit_project_links_project_linked_at
    on audit_project_links (project_id, linked_at desc);

create index idx_audit_project_links_tracked_url_linked_at
    on audit_project_links (tracked_url_id, linked_at desc);

create table audit_run_summaries (
    job_id varchar(64) primary key,
    score integer not null,
    high_issue_count integer not null,
    issue_count integer not null,
    passed_check_count integer not null,
    not_applicable_count integer not null,
    system_error_count integer not null,
    top_issue_key varchar(191),
    top_issue_label varchar(255),
    top_issue_instruction text,
    generated_at timestamp with time zone not null,
    constraint fk_audit_run_summaries_run foreign key (job_id) references audit_runs (job_id) on delete cascade
);

create table audit_run_summary_high_issues (
    id bigint generated by default as identity primary key,
    job_id varchar(64) not null,
    issue_key varchar(191) not null,
    issue_label varchar(255) not null,
    issue_instruction text,
    severity varchar(32) not null,
    constraint fk_audit_run_summary_high_issues_run foreign key (job_id) references audit_runs (job_id) on delete cascade,
    constraint uk_audit_run_summary_high_issues_job_issue unique (job_id, issue_key)
);

create index idx_audit_run_summary_high_issues_job
    on audit_run_summary_high_issues (job_id);
